export const errorCodes = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  USER_NOT_ACTIVE: 'USER_NOT_ACTIVE',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
});
